{{ if .Values.aiEnabled }}
{{ $values := (. | mustDeepCopy) }}
{{ $_ := set $values "common" (dict "nameSuffix" "ai") }}
{{ include "common.deployment.common_config" $values | nindent 0 }}
spec: {{ include "common.deployment.common_spec" $values | nindent 2 }}
  template: {{ include "common.deployment.pod.metadata" $values | nindent 4 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-ai
        image: {{ template "ai.imageName" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env: {{ include "ai.envVariableConfiguration" $values | nindent 10 }}
        ports:
        - name: ai-tcp
          containerPort: 8000
          protocol: TCP
{{ end }}