{{ if .Values.ingressEnabled }}
{{- $port := 8096 -}}
{{- if not .Values.hostNetwork -}}
  {{- $port = .Values.jellyfinServerHttp.port -}}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "cert_helper.secretName" . }}
  namespace: ix-{{ template "common.names.fullname" . }}
spec:
  {{ if eq (include "cert_helper.certAvailable" .) "true" }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ template "cert_helper.secretName" . }}
  {{ end }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "common.names.fullname" . }}-tcp
            port:
              number: {{ (include "port_helper.port" .) }}
        path: {{ .Values.path }}
        pathType: {{ .Values.pathType }}
{{ end }}