apiVersion: v2
appVersion: 1.29.0
dependencies:
- name: common
  repository: file://../../../library/common/2304.0.1
  version: 2304.0.1
description: A photo management system for Nas users
home: https://mtmt.tech/
icon: https://cdn.mtmt.tech/logo-r.png
keywords:
- storage
- cloud
name: mtphotos
version: 1.0.32
