{{ $values := (. | mustDeepCopy) }}
{{ $_ := set $values "common" (dict "nameSuffix" "ui") }}
{{ include "common.deployment.common_config" $values | nindent 0 }}
spec: {{ include "common.deployment.common_spec" $values | nindent 2 }}
  template: {{ include "common.deployment.pod.metadata" $values | nindent 4 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-ui
        image: {{ template "ui.imageName" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: ui-web
          containerPort: 80
          protocol: TCP